### ISSUE TITLE
GVCF output?

### ISSUE THREAD

**Issue by ntm** [anands-repo/hello#2]
hello HELLO,
your tool looks interesting, I'ld like to try it out, but AFAICT it doesn't currently produce GVCF, only VCF. This can be a show-stopper for the n+1 use-case where new samples arrive regularly (and one needs to know if previous samples were HOMOREF or NOCALL). Are there any plans to output GVCF?
Thanks,
Nicolas

**Comment by anands-repo** [comment]
Hi @ntm Thanks for your interest! You are right that currently HELLO only produces VCF. Thank you for your suggestion regarding GVCF. We are yet to complete planning for another release. When we do so, we will definitely consider your suggestion regarding GVCF.
