### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by Mahmoudbassuoni** [anands-repo/hello#3]
Hi, 
I am trying to install the repo but every time I run the make command it gets me this error 
`In file included from /usr/include/boost/python/detail/prefix.hpp:13:0,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /home/ionadmin/hello/main.cpp:2:
/usr/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
compilation terminated.
CMakeFiles/Callability.dir/build.make:75: recipe for target 'CMakeFiles/Callability.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/Callability.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/Callability.dir/all' failed
make[1]: *** [CMakeFiles/Callability.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
`
I am pretty sure that I have the latest cmake version and also I am running this on a remote server so I made sure to create an enviroment for me with all the dependancies installed, so can anyone help with that please ? 

Thanks,

**Comment by anands-repo** [comment]
Hi, It seems boost-Python can’t find the Python include directories. Can
you try fixing the PYTHON_INC variable in CMakeLists.txt to point to the
correct path in your environment?

**Comment by Mahmoudbassuoni** [comment]
Thanks , I have changed the needed directories in the CMakeLists.txt file but now I get this error with the Read. h file 
`In file included from /home/ionadmin/hello/c++/include/Trie.h:8:0,
                 from /home/ionadmin/hello/c++/src/Trie.cpp:2:
/home/ionadmin/hello/c++/include/Read.h: In function ‘std::vector<_RealType> list_converter(const boost::python::list&)’:
/home/ionadmin/hello/c++/include/Read.h:42:9: error: ‘stl_input_iterator’ is not a member of ‘p’
         p::stl_input_iterator<T>(array),`
do you have any idea, what could be the issue ?

**Comment by anands-repo** [comment]
I am not sure ... If I were to venture a guess, I would say this could be a
boost::python installation issue (boost::python requires special steps to
install it correctly compared to regular boost installation) or a version
mismatch between the boost used for HELLO and the installation in the
server.

I would recommend using our Docker environment (obtained through `docker
pull oddjobs/hello_image.x86_64`) and build HELLO inside that.

**Comment by Mahmoudbassuoni** [comment]
I have done it with the docker image, it's much easier. don't know why I didn't do that from the begining lol :)) but thanks for your help,, I am closing this now
